packages:
  - "1. webpack核心功能/*"
  - "2. 常用扩展/*"
  - "2. 常用扩展/*/*"
  - "3. css工程化/*"
  - "4. js兼容性/*"
  - "5. 性能优化/*"
  - "6. 补充和案例/*"
  - "6. 补充和案例/*/*"
  - "6. 补充和案例/*/*/*"
  - "!**/node_modules/**"
